[package]
name = "car_rank_data"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12", features = ["blocking", "json"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1"
chrono = "0.4"